[package]
name = "docker-on-kvm"
version = "0.1.0"
authors = ["Anton Jansson <anton_jansson@live.se>"]
edition = "2018"

[dependencies]
rand = "0.8.0"
regex = "1"
uuid = { version = "0.8", features = ["v4"] }

structopt = "0.3"

virt = "0.2.11"